cc_binary(
    name = "write_batch_worker",
    srcs = [
        "batch_worker.cpp",
        "batch_worker.h",
        "write_batch_worker.cpp"
    ],
    deps = [],
    copts = [
        "-g",
        "-std=c++2a",
    ],
    linkopts = [
        "-lpthread",
    ],
)
